import type { PresetConfig, PresetStyle } from "./shadcn-preset";

// Built-in named presets. Ported from shadcn `packages/shadcn/src/preset/defaults.ts`
// (SHA 98a1fe67b439324ddc857f47fbdce056600a4329), reduced to the codec fields
// so each entry round-trips exactly through encodePreset/decodePreset.
export const DEFAULT_PRESETS = {
  nova: {
    style: "nova",
    baseColor: "neutral",
    theme: "neutral",
    chartColor: "neutral",
    iconLibrary: "lucide",
    font: "geist",
    fontHeading: "inherit",
    menuAccent: "subtle",
    menuColor: "default",
    radius: "default",
  },
  vega: {
    style: "vega",
    baseColor: "neutral",
    theme: "neutral",
    chartColor: "neutral",
    iconLibrary: "lucide",
    font: "inter",
    fontHeading: "inherit",
    menuAccent: "subtle",
    menuColor: "default",
    radius: "default",
  },
  maia: {
    style: "maia",
    baseColor: "neutral",
    theme: "neutral",
    chartColor: "neutral",
    iconLibrary: "hugeicons",
    font: "figtree",
    fontHeading: "inherit",
    menuAccent: "subtle",
    menuColor: "default",
    radius: "default",
  },
  lyra: {
    style: "lyra",
    baseColor: "neutral",
    theme: "neutral",
    chartColor: "neutral",
    iconLibrary: "phosphor",
    font: "jetbrains-mono",
    fontHeading: "inherit",
    menuAccent: "subtle",
    menuColor: "default",
    radius: "default",
  },
  mira: {
    style: "mira",
    baseColor: "neutral",
    theme: "neutral",
    chartColor: "neutral",
    iconLibrary: "hugeicons",
    font: "inter",
    fontHeading: "inherit",
    menuAccent: "subtle",
    menuColor: "default",
    radius: "default",
  },
  luma: {
    style: "luma",
    baseColor: "neutral",
    theme: "neutral",
    chartColor: "neutral",
    iconLibrary: "lucide",
    font: "inter",
    fontHeading: "inherit",
    menuAccent: "subtle",
    menuColor: "default",
    radius: "default",
  },
  sera: {
    style: "sera",
    baseColor: "taupe",
    theme: "taupe",
    chartColor: "taupe",
    iconLibrary: "lucide",
    font: "noto-sans",
    fontHeading: "playfair-display",
    menuAccent: "subtle",
    menuColor: "default",
    radius: "default",
  },
  rhea: {
    style: "rhea",
    baseColor: "neutral",
    theme: "neutral",
    chartColor: "neutral",
    iconLibrary: "lucide",
    font: "inter",
    fontHeading: "inherit",
    menuAccent: "subtle",
    menuColor: "default",
    radius: "default",
  },
} satisfies Record<PresetStyle, PresetConfig>;

export type DefaultPresets = typeof DEFAULT_PRESETS;
export type DefaultPresetName = keyof DefaultPresets;
