export { type TemplateData, processTemplatesFromPrefix, hasTemplatesWithPrefix } from "./utils";
export { processFrontendTemplates } from "./frontend";
export { processBackendTemplates } from "./backend";
export { processDbTemplates } from "./database";
export { processApiTemplates } from "./api";
export { processBaseTemplate } from "./base";
export { processConfigPackage } from "./packages";
export { processEnvPackage } from "./packages";
export { processCloudflarePackage } from "./packages";
export { processUiPackage } from "./packages";
export { processAuthTemplates } from "./auth";
export { processPaymentsTemplates } from "./payments";
export { processAddonTemplates } from "./addons";
export { processExampleTemplates } from "./examples";
export { processExtrasTemplates } from "./extras";
export { processDeployTemplates } from "./deploy";
export { processEmailTemplates } from "./email";
export { processI18nTemplates } from "./i18n";
